ezsystems/ezplatform-kernel

Readme.md
appveyor.yml
bin/extract-translations.sh
eZ/Bundle/EzPublishCoreBundle/Resources/config/papi.yml
eZ/Bundle/EzPublishCoreBundle/behat_suites.yml
eZ/Bundle/PlatformInstallerBundle/src/DependencyInjection/Compiler/InstallerTagPass.php
eZ/Publish/Core/Helper/FieldsGroups/ArrayTranslatorFieldsGroupsList.php
eZ/Publish/Core/Helper/FieldsGroups/FieldsGroupsList.php
eZ/Publish/Core/Helper/FieldsGroups/RepositoryConfigFieldsGroupsListFactory.php

| **JIRA issue**                          | [EZP-31007](https://jira.ez.no/browse/EZP-31007)
| **Tests pass**                          | not configured yet
| **Doc needed**                       | not yet
This PR replaces references to ezpublish-kernel with ezplatform-kernel.

Replaced references to ezpublish-kernel with ezplatform-kernel

---

.travis.yml

Attempting to fix failing Behat job.

[Travis] Explicitly set PHP 7.3 for Behat job

---

eZ/Publish/API/Repository/Tests/BaseTest.php
eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php
eZ/Publish/API/Repository/Tests/UserServiceTest.php
eZ/Publish/Core/FieldType/Tests/UserTest.php
eZ/Publish/Core/FieldType/User/Type.php
eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/UserConverter.php

| **JIRA issue**                          | [EZP-31079](https://jira.ez.no/browse/EZP-31079)
- https://github.com/ezsystems/ezplatform-admin-ui/pull/1288
- https://github.com/ezsystems/ezplatform-content-forms/pull/17
- https://github.com/ezsystems/ezplatform-user/pull/62

EZP-31079: Provided validation for email uniqueness and login pattern

---

eZ/Publish/API/Repository/Events/Role/BeforeCopyRoleEvent.php
eZ/Publish/API/Repository/Events/Role/CopyRoleEvent.php
eZ/Publish/API/Repository/RoleService.php
eZ/Publish/API/Repository/Tests/RoleServiceTest.php
eZ/Publish/API/Repository/Values/User/Role.php
eZ/Publish/API/Repository/Values/User/RoleCopyStruct.php
eZ/Publish/Core/Event/RoleService.php
eZ/Publish/Core/Persistence/Cache/UserHandler.php
eZ/Publish/Core/Persistence/Legacy/User/Handler.php
eZ/Publish/Core/Persistence/Legacy/User/Mapper.php
eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway.php
eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway/DoctrineDatabase.php
eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway/ExceptionConversion.php
eZ/Publish/Core/Repository/Helper/RoleDomainMapper.php
eZ/Publish/Core/Repository/RoleService.php
eZ/Publish/Core/Repository/Values/User/RoleCopyStruct.php
eZ/Publish/SPI/Persistence/User/Handler.php
eZ/Publish/SPI/Persistence/User/RoleCopyStruct.php
eZ/Publish/SPI/Repository/Decorator/RoleServiceDecorator.php

| **JIRA issue**                          | [EZP-31383](https://jira.ez.no/browse/EZP-31383)
| **Original PR**                        | ezsystems/ezpublish-kernel#3009
| **Target eZ Platform version** | `ezplatform-kernel:1.0`
Prepared `ezplatform-kernel` for `Role` copying functionality.
Added `copyRole` method to `RoleService` API Interface with `Core` and `Event` implementations.
Created related structs and `Database Gateway` and `User\Handler` implementations.
Added `Role` copying …

EZP-31383: Implemented Role copying API

---

eZ/Bundle/EzPublishCoreBundle/URLChecker/Handler/AbstractConfigResolverBasedURLHandler.php
eZ/Bundle/EzPublishCoreBundle/URLChecker/Handler/HTTPHandler.php

| **JIRA issue**                          | [EZP-31544](https://jira.ez.no/browse/EZP-31544)
Corrected some variables after removed dynamic settings

EZP-31544: changed $configResolver from private to protected and changed variable

---

eZ/Publish/Core/settings/repository/inner.yml

| **JIRA issue**                          | [EZP-31580](https://jira.ez.no/browse/EZP-31580)
| **Tests pass**                          | I hope
Fixed injection of User Handler into PermissionResolver.
This change reduces amount of database queries from ~576 to ~132 in AdminUI.

EZP-31580: Fixed injection of User Handler into PermissionResolver

---

.travis.yml
eZ/Publish/API/Repository/Tests/SearchService/DeleteTranslationTest.php
eZ/Publish/API/Repository/Tests/SearchServiceTest.php
eZ/Publish/Core/Search/Common/EventSubscriber/ContentEventSubscriber.php
eZ/Publish/SPI/Search/ContentTranslationHandler.php

Technical PR to test merge up of ezsystems/ezpublish-kernel#3013 ([EZP-31420](https://jira.ez.no/browse/EZP-31420)).

Merged up EZP-31420

---

.travis.yml

| **JIRA issue**                          | https://jira.ez.no/browse/EZP-31613
| **Type**                                   | fix?
| **Target eZ Platform version** | v3
Regenerated Slack integration after workspace name change.
BTW separate PR for ezpublish-kernel 6.13 is coming as well.

[Travis] Changed ezplatform-kernel notification key after rebranding

---

.travis.yml

| **Target eZ Platform version** | `v3.x` 
Updated Solr from 7.7.2 to 7.7.3 (last 7.X patch release) in `.travis.yml`.

Updated Solr version to 7.7.3 in .travis.yml

---

eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
eZ/Publish/API/Repository/ContentService.php
eZ/Publish/API/Repository/Events/Content/BeforeCreateContentEvent.php
eZ/Publish/API/Repository/Events/Content/BeforeUpdateContentEvent.php
eZ/Publish/API/Repository/Events/Content/CreateContentEvent.php
eZ/Publish/API/Repository/Events/Content/UpdateContentEvent.php
eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
eZ/Publish/Core/Event/ContentService.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/Mapper/ContentMapper.php
eZ/Publish/Core/Repository/Repository.php
eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php
eZ/Publish/Core/Repository/Strategy/ContentValidator/ContentValidatorStrategy.php
eZ/Publish/Core/Repository/Tests/ContentValidator/ContentValidatorStrategyTest.php
eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
eZ/Publish/Core/Repository/Validator/ContentCreateStructValidator.php
eZ/Publish/Core/Repository/Validator/ContentUpdateStructValidator.php
eZ/Publish/Core/Repository/Validator/VersionValidator.php
eZ/Publish/Core/settings/repository/inner.yml
eZ/Publish/SPI/Repository/Decorator/ContentServiceDecorator.php
eZ/Publish/SPI/Repository/Validator/ContentValidator.php

| **JIRA issue**                          | [EZP-31574](https://jira.ez.no/browse/EZP-31574)
| **Tests pass**                          | no

EZP-31574: Added posibility to save and preview incomplete draft

---

composer.json

| **JIRA issue**                          | [EZP-31688](https://jira.ez.no/browse/EZP-31688)

EZP-31688: Removed obsolete forked 3rd party packages

---

eZ/Publish/Core/Persistence/Legacy/Filter/Gateway/Content/Doctrine/DoctrineGateway.php
eZ/Publish/Core/Persistence/Legacy/Filter/Gateway/Location/Doctrine/DoctrineGateway.php

Getting database platform in a constructor seems like a bad idea on an instance without any database settings yet (after e.g. composer create-project)
TODO:

Fixed getting DB platform in Filtering Gateways to be lazy

---

eZ/Publish/API/Repository/Tests/ContentServiceTest.php
eZ/Publish/API/Repository/Tests/PermissionResolverTest.php
eZ/Publish/Core/Repository/ContentService.php
eZ/Publish/Core/Repository/Mapper/ContentMapper.php
eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
eZ/Publish/Core/Repository/Validator/VersionValidator.php
eZ/Publish/Core/settings/repository/inner.yml
eZ/Publish/SPI/Limitation/Target/Builder/VersionBuilder.php
eZ/Publish/SPI/Limitation/Target/Version.php

| **JIRA issue**                          | [EZEE-3176](https://jira.ez.no/browse/EZEE-3176)

EZEE-3176: Reduced scope of content changes to new and updated fields

---

eZ/Publish/Core/Repository/LocationResolver/PermissionAwareLocationResolver.php

| **JIRA issue**                          | [EZP-31584](https://jira.ez.no/browse/EZP-31584)
| **Target eZ Platform version** | v3.1
Added additional condition to `LocationResolver`.

EZP-31584: Fix broken tests for LocationResolver

---

eZ/Publish/Core/MVC/Symfony/Security/Authentication/RememberMeRepositoryAuthenticationProvider.php

| **JIRA issue**                          | [EZP-31773](https://jira.ez.no/browse/EZP-31773)
| **Tests pass**                          | yes/no
Check first if the token is an ez user else pass it on so the interactive login will do it's job and update the user with a wrapped user.

[EZP-31773] Remember me support multiple user providers

---

eZ/Publish/Core/FieldType/ImageAsset/ImageAssetThumbnailStrategy.php

| **JIRA issue**                          | EZEE-3287
Same as here:
https://github.com/ezsystems/ezplatform-kernel/pull/98

EZEE-3287: Cast destinationId to int for content loading

---

data/mysql/cleandata.sql
data/postgresql/cleandata.sql

https://jira.ez.no/browse/EZP-32040
Related with: https://github.com/ezsystems/ezplatform/pull/614

EZP-32040: Changed welcome page descriptions

---

eZ/Publish/API/Repository/Tests/SearchServiceAggregationTest.php

Fixed the following CI failure: https://travis-ci.com/github/ezsystems/ezplatform-kernel/jobs/401922968

Fixed timezone issues in SearchServiceAggregationTest

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
eZ/Publish/Core/MVC/Symfony/View/Builder/Registry/ControllerMatch.php

| **JIRA issue**                          | EZP-32067
https://github.com/ezsystems/ezplatform-admin-ui/pull/1636
https://github.com/ezsystems/ezplatform-search/pull/11
https://github.com/ezsystems/ezplatform-user/pull/82
https://github.com/ezsystems/ezplatform-connector-dam/pull/22
https://github.com/ezsystems/ezplatform-content-forms/pull/35
https://github.com/ezsystems/ez-support-tools/pull/70

EZP-32067: Injected tagged View Builders into View Builder registry

---

COPYRIGHT
LICENSE
LICENSE-bul
Readme.md

| **JIRA issue**                          | [EZEE-3422](https://issues.ibexa.co/browse/EZEE-3422)
This PR creates or updates LICENSE, LICENSE-bul, COPYRIGHT and README files according to new requirements for Ibexa v3.3 release.

EZEE-3422: Prepared LICENSE and COPYRIGHT files for 3.3 release

---

eZ/Publish/API/Repository/Values/Content/Thumbnail.php

| **Target eZ Platform version** | `3.x`

Added missing @property-read annotations to Thumbnail class

---

eZ/Publish/SPI/FieldType/BinaryBase/PathGeneratorInterface.php
eZ/Publish/SPI/FieldType/BinaryBase/RouteAwarePathGenerator.php

Fixed code style

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/Security/login.html.twig

| **JIRA issue**                          | [IBX-268](https://issues.ibexa.co/browse/IBX-268)
| **Type**                                   | feature/bug/improvement
| **Target eZ Platform version** | `v4.0`
| **Doc needed**                       | ???
Main PR: ezsystems/ezplatform-admin-ui#1755

IBX-268: Redesign buttons for 4.0

---

eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php

Merge up PR for: https://github.com/ezsystems/ezpublish-kernel/pull/3107

Added missing key in ContentTypeHandler

---

eZ/Publish/Core/Persistence/Cache/ObjectStateHandler.php
eZ/Publish/Core/Persistence/Cache/Tests/AbstractBaseHandlerTest.php
eZ/Publish/Core/settings/storage_engines/cache.yml

Merge up PR for: https://github.com/ezsystems/ezpublish-kernel/pull/3106

IBX-569: Changed ObjectStateHandler to extend AbstractInMemoryPersistenceHandler

---

eZ/Publish/API/Repository/SettingService.php
eZ/Publish/Core/Repository/SettingService.php

Documented \eZ\Publish\API\Repository\SettingService exceptions

---

eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/DoctrineStorage.php

| **JIRA issue**                          | [IBX-605](https://issues.ibexa.co/browse/IBX-605)
Narrowing down the potentially deletable URLs will result in getting rid of database deadlocks.

IBX-605: Refactored and optimized orphaned URLs deleting

---

eZ/Bundle/EzPublishCoreBundle/Resources/config/locale.yml

| **JIRA issue**                          |
| **Target eZ Platform version** | ?

Added support for all Belgium national languages 🇧🇪

---

eZ/Bundle/EzPublishCoreBundle/Resources/views/pagelayout.html.twig

| **Target Ibexa version** | `v4.0`

Changed generator name to Ibexa DXP

---

eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php

Permission issue error message is unclear and can lead to confusion
| **Target eZ Platform version** | `v3.x` all of them

Permission issue error message is unclear and can lead to confusion

---

.travis.yml
bin/.travis/prepare_unittest.sh
composer.json
eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
eZ/Bundle/EzPublishCoreBundle/Resources/views/Security/login.html.twig
eZ/Publish/Core/settings/tests/common.yml

See https://github.com/ezsystems/ezplatform-kernel/commit/845108cf9c769c588fd3a6393c8ba1c422b2b306

Reverted changes from master accidentally merged to 1.3
