ezsystems/ezplatform-kernel

- .travis.yml
This PR updates tokens for Travis notifications for Slack. Old tokens were configured for `ezpublish-kernel` repository and won't work here.
> [Travis] Enabled notifications for Slack

- .travis.yml
Provided names to all the jobs so an entire build is more readable.
Extra (for fast forward merge): Dropped obsolete commented-out job trying to use SiteAccess-aware Repository layer (it's enabled now by default, so all integration tests rely on it).
> [Travis] Named all jobs for better readability

- eZ/Publish/API/Repository/UserService.php
| **Type**                                   |  bug
| **Target eZ Platform version** | -
| **Tests pass**                          | no
Removed `@deprecated` annotation from `UserService::loadUserByLogin`. Propably conflicts has been incorrect resolved during the merge up.
> Removed @deprecated annotation from UserService::loadUserByLogin

- eZ/Publish/API/Repository/Tests/BaseTest.php
- eZ/Publish/Core/FieldType/Tests/Integration/BaseCoreFieldTypeIntegrationTest.php
| **Target eZ Platform version** | `v3.0` internal test framework
| **Tests pass**                          | TBD
The `ezpublish.persistence.connection` service is a more stable abstraction than `ezpublish.api.storage_engine.legacy.connection`. 
While the latter one is available for tests ran on `ezplatform-kernel` due to [some Container tricks](https://github.com/ezsystems/ezplatform-kernel/blob/0a7dac34e860d6aa179944bf42e9af2f4b43b0b1/eZ/Publish/Core/settings/containerBuilder.php#L87), it's not easily propagated to the dependencies, …
> Fixed integration tests to rely on `ezpublish.persistence.connection`

- doc/bc/changes-1.0.md
- eZ/Publish/API/Repository/ContentService.php
- eZ/Publish/Core/Persistence/Cache/ContentHandler.php
- eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
- eZ/Publish/Core/Repository/ContentService.php
- eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
- eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php
- eZ/Publish/SPI/Persistence/Content/Handler.php
- eZ/Publish/SPI/Repository/Decorator/ContentServiceDecorator.php
- eZ/Publish/SPI/Repository/Tests/Decorator/ContentServiceDecoratorTest.php
| **JIRA issue**                          | [EZP-30928](https://jira.ez.no/browse/EZP-30928)
Dropped deprecated API `\eZ\Publish\API\Repository\ContentService::removeTranslation`. Use `\eZ\Publish\API\Repository\ContentService::deleteTranslation` instead.
Dropped deprecated SPI `\eZ\Publish\SPI\Persistence\Content\Handler::removeTranslationFromContent`. Use \eZ\Publish\SPI\Persistence\Content\Handler::deleteTranslationFromContent …
> EZP-30928: Dropped deprecated ContentService::removeTranslation method

- eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/ConsoleCommandListenerTest.php
- eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
- eZ/Publish/API/Repository/Tests/ContentServiceTest.php
- eZ/Publish/API/Repository/Tests/LocationServiceTest.php
- eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterTest.php
| **Target eZ Platform version** | `3.0`
`expectExceptionMessageRegExp()` has been deprecated in PHPUnit 8 in favour of `expectExceptionMessageMatches()` and will be removed in PHPUnit 9.
Example of failing job: https://travis-ci.com/github/ezsystems/ezplatform-kernel/jobs/309701520
> Replaced usages of deprecated expectExceptionMessageRegExp() with expectExceptionMessageMatches()

- eZ/Publish/API/Repository/Tests/BaseTest.php
- eZ/Publish/API/Repository/Tests/URLAliasServiceTest.php
- eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Mapper.php
| **JIRA issue**                          | [EZEE-3069](https://jira.ez.no/browse/EZEE-3069)
| **Target eZ Platform version** | `3.0`
According to doc: if url alias type is `URLAlias::LOCATION` then `destination` property contains location id which should be typeof int.  
Actual bugfix: https://github.com/ezsystems/ezplatform-kernel/pull/26/files#diff-50956c9b2b9e4174ee6c9013cf358264R111
Actual test: https://github.com/ezsystems/ezplatform-kernel/pull/26/files#diff-ce61cc0866ae34a229c2e0d3 …
> EZEE-3069: Ensured type of $destination property value is int for location based url aliases

- eZ/Publish/Core/Search/Common/IncrementalIndexer.php
- eZ/Publish/Core/Search/Common/Indexer.php
- eZ/Publish/Core/Search/Legacy/Content/Indexer.php
- eZ/Publish/Core/settings/search_engines/legacy.yml
| **JIRA issue**                          | [EZP-31517](https://jira.ez.no/browse/EZP-31517) blocking [EZP-30921](https://jira.ez.no/browse/EZP-30921)
| **Required by**                        | ezsystems/ezplatform-solr-search-engine#177
This PR refactors Search Indexers to rely on Doctrine Connection instead of Database Handler from Zeta Components.
Additionally Indexer code relied on deprecated SPI `ContentInfo::$isPublished` property, …
> EZP-31517: Refactored Search Indexers to rely on Doctrine\DBAL

- eZ/Publish/Core/Search/Legacy/Content/WordIndexer/Gateway/DoctrineDatabase.php
- eZ/Publish/Core/Search/Legacy/Content/WordIndexer/Repository/SearchIndex.php
- eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerContentSortTest.php
- eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerContentTest.php
- eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerLocationSortTest.php
- eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerLocationTest.php
- eZ/Publish/Core/settings/search_engines/legacy.yml
- eZ/Publish/Core/settings/search_engines/legacy/indexer.yml
| **JIRA issue**                          | [EZP-31301](https://jira.ez.no/browse/EZP-31301) blocking [EZP-30921](https://jira.ez.no/browse/EZP-30921)
| **Related to**                           | #10
This PR replaces eZc `DatabaseHandler` with Doctrine `Connection` and `QueryBuilder` in Word Indexer gateways (the ones called "under the hood" for `ezplatform:reindex` for LSE).
Note: please look past confusing naming (I should refactor it as …
> EZP-31301: Refactored WordIndexer SearchIndex GW to rely on Doctrine

- doc/bc/changes-1.0.md
- eZ/Publish/API/Repository/Tests/URLServiceTest.php
- eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriteriaConverterTest.php
- eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/CriterionHandlerTest.php
- eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/LogicalAndTest.php
- eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/LogicalNotTest.php
- eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/LogicalOrTest.php
- eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/MatchAllTest.php
- eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/MatchNoneTest.php
- eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/PatternTest.php
- eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/ValidityTest.php
- eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/VisibleOnlyTest.php
- eZ/Publish/Core/Persistence/Legacy/URL/Gateway.php
- eZ/Publish/Core/Persistence/Legacy/URL/Gateway/DoctrineDatabase.php
- eZ/Publish/Core/Persistence/Legacy/URL/Query/CriteriaConverter.php
- eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler.php
- eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/Base.php
- eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/LogicalAnd.php
- eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/LogicalNot.php
- eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/LogicalOr.php
- eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/MatchAll.php
- eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/MatchNone.php
- eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/Pattern.php
- eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/SectionId.php
- eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/SectionIdentifier.php
- eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/Validity.php
- eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/VisibleOnly.php
- eZ/Publish/Core/settings/storage_engines/legacy/url.yml
| **JIRA issue**                          | [EZP-31300](https://jira.ez.no/browse/EZP-31300) blocking [EZP-30921](https://jira.ez.no/browse/EZP-30921) (#11)
| **Tests pass**                          | [yes](https://travis-ci.com/github/ezsystems/ezplatform-kernel/builds/156384093)
This PR replaces usages of eZc `DatabaseHandler` with Doctrine `Connection` and `QueryBuilder` in URL Search Gateway and Criteria handlers. The alignment of tests is separated from production code changes …
> EZP-31300: Refactored URL Search GW and handlers to rely on Doctrine

- doc/bc/changes-1.0.md
- eZ/Publish/API/Repository/Tests/FieldType/SearchBaseIntegrationTest.php
- eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/FieldValue/Handler.php
- eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/FieldValue/Handler/Collection.php
| **JIRA issue**                          | [EZP-30392](https://jira.ez.no/browse/EZP-30392)
This PR drops deprecated support for `%` sign as a wildcard operator in the Legacy (SQL) Search Engine. Search API consumer should use `*` instead.
> EZP-30392: [LSE] Dropped deprecated support for `%` as a wildcard

- eZ/Publish/API/Repository/Tests/UserServiceTest.php
- eZ/Publish/Core/FieldType/User/Type.php
| **JIRA issue**                          | [EZP-31012](https://jira.ez.no/browse/EZP-31012)
`\eZ\Publish\Core\FieldType\User\Value::$passwordUpdatedAt` should be updated together with `\eZ\Publish\Core\FieldType\User\Value::$passwordHashType`
Example failing build https://travis-ci.com/github/ezsystems/ezplatform-kernel/jobs/311199510)
> EZP-31012: Fixed conversion to persistence value in ezuser field type (empty passwordUpdateAt)

- eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php
| **JIRA issue**                          | [EZP-31527](https://jira.ez.no/browse/EZP-31527)
Right now `ezplatform.core.command.reindex` command does not show ETA. It is very useful to have this information on big projects where the script execution can take 5+ hours.
> EZP-31527: Changed ProgressBar of ezplatform:reindex command to be very verbose

- eZ/Bundle/EzPublishCoreBundle/Command/RegenerateUrlAliasesCommand.php
| **JIRA issue**                          | [EZP-31529](https://jira.ez.no/browse/EZP-31529)
Regenerate URL aliases command is an important part of upgrade scripts. And because it ignores `no-interaction` option it is much harder to automate the upgrade scripts.
> EZP-31529: Added --no-interaction option to cmd regenerating URL aliases

- eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
- eZ/Bundle/EzPublishCoreBundle/EventListener/RejectExplicitFrontControllerRequestsListener.php
- eZ/Bundle/EzPublishCoreBundle/Resources/config/http_kernel.yml
- eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/RejectExplicitFrontControllerRequestsListenerTest.php
This PR merges https://github.com/ezsystems/ezpublish-kernel/pull/3010 to `master`. I need another round of QA to make sure changed implementation is working in v3.
> EZP-31519: Move app.php rejection snippet from front controller to ezpublish-kernel 

- eZ/Publish/Core/Persistence/Cache/UserHandler.php
| **JIRA issue**                          | [EZP-31536](https://jira.ez.no/browse/EZP-31536)
| **Target eZ Platform version** | `3.0`
The following PAPI calls sequence
```
$this->repository->getUserService()->loadUserByLogin('admin');
$this->repository->getUserService()->loadUsersByEmail('nospam@ez.no');
```
will cause the error
```
Return value of eZ\Publish\Core\Persistence\Cache\UserHandler::loadUsersByEmail() must be of the type array, object returned
``` …
> EZP-31536: Fixed cache corruption for the ez-users-<email>-by-email key

- composer.json
- eZ/Bundle/EzPublishDebugBundle/Resources/views/Profiler/persistence/panel.html.twig
| **JIRA issue**                          | [EZEE-3091](https://jira.ez.no/browse/EZEE-3091)
Before SiteAccess factory, there were only scalar values used in `$arguments` array in `\eZ\Publish\Core\Persistence\Cache\PersistenceLogger::logCall` method.
When object was used it unsuccessfully tried to cast it to string.
> EZEE-3091: Used twig dump to display object arguments

- eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
| **JIRA issue**                          | [EZP-30465](https://jira.ez.no/browse/EZP-30465)
| **Target eZ Platform version** | `v3.0.1`
`CopySubtreeCommand` and `ResizeOriginalImagesCommand` Symfony commands were injected with PermissionResolver using expression language (`@=service('ezpublish.api.repository').getPermissionResolver()`). 
This might lead to an existence of two different instances of `PermissionResolver` accross the application when used with command.
Sanities for Symfony …
> EZP-30465: Fixed PermissionResolver injection into commands

- eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
- eZ/Publish/Core/IO/ConfigScopeChangeAwareIOService.php
- eZ/Publish/Core/IO/Tests/ConfigScopeChangeAwareIOServiceTest.php
| **JIRA issue**                          | [EZP-31546](https://jira.ez.no/browse/EZP-31546)
| **Target eZ Platform version** | `v3.0.1`
> EZP-31546: Fixed ignored path prefixes for binaries and images

- eZ/Publish/API/Repository/Tests/UserServiceTest.php
| **JIRA issue**                          | [EZP-31012](https://jira.ez.no/browse/EZP-31012)
| **Target eZ Platform version** | `3.0.0`
Fixed assertion for `passwordUpdateAt` value in `eZ\Publish\API\Repository\Tests\UserServiceTest::testUpdateUserUpdatesExpectedProperties`. The previous approach might lead to false-negative build results (because it was time sensitive). 
Follow up for https://github.com/ezsystems/ezplatform-kernel/pull/30.
> EZP-31012: Fixed assertion for passwordUpdateAt value in UserServiceTest::testUpdateUserUpdatesExpectedProperties

- eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
- eZ/Publish/API/Repository/PermissionService.php
- eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
- eZ/Publish/Core/Repository/Permission/CachedPermissionService.php
- eZ/Publish/Core/Repository/Repository.php
- eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
- eZ/Publish/Core/settings/repository/autowire.yml
- eZ/Publish/Core/settings/repository/inner.yml
| **~JIRA~ issue**                          | Part of  #44 
Introducing API `PermissionService` to avoid types mismatch in `Repository`. It extends `PermissionResolver` and `PermissionCriterionResolver` interfaces as this is what is actually returned by injecting `CachedPermissionService`.
> EZP-30465: Introduced PermissionService

- eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
- eZ/Publish/API/Repository/PermissionService.php
- eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
- eZ/Publish/Core/Helper/Tests/ContentInfoLocationLoader/SudoMainLocationLoaderTest.php
- eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/BaseTest.php
- eZ/Publish/Core/MVC/Symfony/Routing/Tests/UrlAliasGeneratorTest.php
- eZ/Publish/Core/MVC/Symfony/Security/Tests/Authentication/RememberMeRepositoryAuthenticationProviderTest.php
- eZ/Publish/Core/Repository/Permission/CachedPermissionService.php
- eZ/Publish/Core/Repository/Permission/PermissionCriterionResolver.php
- eZ/Publish/Core/Repository/Permission/PermissionResolver.php
- eZ/Publish/Core/Repository/Repository.php
- eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
- eZ/Publish/Core/Repository/Tests/Service/Mock/PermissionTest.php
- eZ/Publish/Core/settings/repository/autowire.yml
- eZ/Publish/Core/settings/repository/inner.yml
- eZ/Publish/Core/settings/settings.yml
| **JIRA issue**                          | [EZP-30465](https://jira.ez.no/browse/EZP-30465)
> EZP-30465: Changed the way PermissionResolver is built to make it reusable

- eZ/Bundle/EzPublishCoreBundle/Resources/config/locale.yml
- eZ/Publish/Core/MVC/Symfony/Locale/LocaleConverterInterface.php
| **JIRA issue**                          | [EZP-31591](https://jira.ez.no/browse/EZP-31591)
This PR adds missing support for Farsi (Persian) language.
> EZP-31591: Farsi (Persian) language is missing in internal locale conversion map

- .travis.yml
- eZ/Publish/API/Repository/Tests/FieldType/SearchBaseIntegrationTest.php
- eZ/Publish/Core/FieldType/BinaryFile/SearchField.php
- eZ/Publish/Core/FieldType/DateAndTime/SearchField.php
- eZ/Publish/Core/FieldType/Image/SearchField.php
- eZ/Publish/Core/FieldType/MapLocation/SearchField.php
- eZ/Publish/Core/FieldType/Media/SearchField.php
- eZ/Publish/Core/FieldType/Relation/Type.php
- eZ/Publish/Core/FieldType/Tests/Url/UrlStorageTest.php
- eZ/Publish/Core/FieldType/Tests/UserTest.php
- eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/AuthorConverter.php
- eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/DateAndTimeConverter.php
- eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/DateConverter.php
- eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/TimeConverter.php
- eZ/Publish/Core/Persistence/Legacy/Tests/Content/ContentHandlerTest.php
- eZ/Publish/Core/Persistence/TransformationProcessor/PcreCompiler.php
- eZ/Publish/Core/Repository/Tests/Service/Mock/UserPreferenceTest.php
- eZ/Publish/Core/Repository/UserPreferenceService.php
| **JIRA issue**                          | [EZP-31542](https://jira.ez.no/browse/EZP-31542)
The most significant changes from our perspective: 
```
Trying to use values of type null, bool, int, float or resource as an array (such as $null["key"]) will now generate a notice. This does not affect array accesses performed by list(). RFC: https://wiki.php.net/rfc/notice-for-non-valid-array-container
```
```
Passing invalid characters to ''base_convert()'', ''bindec()'', ''octdec()'' …
```
> EZP-31542: Added PHP 7.4 support  (eZ Platform 3.0)

- eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Cache/Resolver/ProxyResolverTest.php
- eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Cache/Resolver/RelativeResolverTest.php
- eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Cache/ResolverFactoryTest.php
- eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/ImageAsset/AliasGeneratorTest.php
- eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/PlaceholderAliasGeneratorTest.php
- eZ/Publish/API/Repository/Tests/FieldType/BaseIntegrationTest.php
- eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php
- eZ/Publish/Core/FieldType/Tests/ImageAsset/AssetMapperTest.php
- eZ/Publish/Core/Repository/SiteAccessAware/Tests/AbstractServiceTest.php
- eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
- eZ/Publish/Core/Repository/Tests/Service/Mock/UrlAliasTest.php
- eZ/Publish/SPI/FieldType/Tests/FieldTypeTest.php
| **Target version** | test setup for eZ Platform Kernel 1.0
We still had used some PHPUnit class names from `\PHPUnit_Framework_*` which were finally dropped in PHPUnit 8.
It applied to `MockObject` usage and exception expectations. For the latter one a more correct fix was due, which simplified our code a bit. While at it, some missing exception-related imports were fixed.
> [Tests] Fixed obsolete PHPUnit class names

- composer.json
| **Target eZ Platform version** | Behat setup of `v3.0`
When moving our own BehatBundle out of Kernel, we've missed the fact that it installed dependencies providing `Behat\*` namespaces. Since Kernel defines its own Behat contexts, it's reasonable to `require-dev` the minimum set of dependencies:
* `behat/behat` providing `Behat\Behat`, used in all Contexts, e.g. in [BasicContentContext](https://github.com/ezsystems/ezplatform-kernel/blob/v1.0.2/eZ/Bundle/EzPublishCoreBundle/Features/Context/BasicContentContext.php#L9)
* `friends-of-behat/mink-extension` providing …
> [Composer] Restored required Behat dev dependencies

- eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
- eZ/Publish/API/Repository/Events/URLWildcard/BeforeUpdateEvent.php
- eZ/Publish/API/Repository/Events/URLWildcard/UpdateEvent.php
- eZ/Publish/API/Repository/Tests/URLWildcardServiceTest.php
- eZ/Publish/API/Repository/URLWildcardService.php
- eZ/Publish/API/Repository/Values/Content/URLWildcardStruct.php
- eZ/Publish/API/Repository/Values/Content/URLWildcardUpdateStruct.php
- eZ/Publish/Core/Event/Tests/URLWildcardServiceTest.php
- eZ/Publish/Core/Event/URLWildcardService.php
- eZ/Publish/Core/Persistence/Cache/Tests/UrlWildcardHandlerTest.php
- eZ/Publish/Core/Persistence/Cache/UrlWildcardHandler.php
- eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway.php
- eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway/DoctrineDatabase.php
- eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway/ExceptionConversion.php
- eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Handler.php
- eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlWildcard/UrlWildcardHandlerTest.php
- eZ/Publish/Core/Repository/URLWildcardService.php
- eZ/Publish/SPI/Persistence/Content/UrlWildcard/Handler.php
- eZ/Publish/SPI/Repository/Decorator/URLWildcardServiceDecorator.php
| **JIRA issue**                          | https://jira.ez.no/browse/EZP-31590
> EZP-31590: Added update feature for URL Wildcards

- eZ/Publish/Core/Search/Common/EventSubscriber/LocationEventSubscriber.php
- eZ/Publish/Core/Search/Tests/Common/LocationEventSubscriber/LocationEventSubscriberTest.php
| **JIRA issue**                          | [EZP-31663](https://jira.ez.no/browse/EZP-31663)
| **Target eZ Platform version** | `3.1`
Added missing `\eZ\Publish\SPI\Search\Handler::indexLocation` call in `\eZ\Publish\Core\Search\Common\EventSubscriber\LocationEventSubscriber::onCreateLocation`  + unit tests 
This change doen't have impact on Solr integration (ref. https://github.com/ezsystems/ezplatform-solr-search-engine/blob/master/lib/Handler.php#L271-L280) however …
> EZP-31663: Trigger location indexing after LocationService::createLocation

- composer.json
| **JIRA issue**                          | n/a
| **Type**                                   | Composer stable branch configuration
| **Target eZ Platform version** | changes for 1.0 branch only, need to be reverted in master
1.0 branch has invalid branch alias set for Composer and is running tests using incorrect metareporitory and wrong dependencies. This PR fixes that.
> [Composer] Set branch alias and dependencies for branch 1.0

- eZ/Publish/Core/Helper/FieldsGroups/ArrayTranslatorFieldsGroupsList.php
- eZ/Publish/Core/Helper/FieldsGroups/FieldsGroupsList.php
- eZ/Publish/Core/Helper/Tests/FieldsGroups/ArrayTranslatorFieldsGroupsListTest.php
| **JIRA issue**                          | https://jira.ez.no/browse/EZP-31344
Added getFieldGroup method for FieldsGroupsList implementation.
Related PR: https://github.com/ezsystems/ezplatform-content-forms/pull/26
> EZP-31344: Added getFieldGroup method

- eZ/Publish/Core/Repository/Validator/VersionValidator.php
| **JIRA issue**                          | [EZEE-3191](https://jira.ez.no/browse/EZEE-3191)
> EZEE-3191: Fixed wrong array key used in Version validation

- eZ/Bundle/EzPublishCoreBundle/Resources/config/papi.yml
| **JIRA issue**                          | [EZP-31701](https://jira.ez.no/browse/EZP-31701)
| **Target eZ Platform version** | `3.0`
`ez publish.api.search engine` depends on repository configuration
https://github.com/ezsystems/ezplatform-kernel/blob/b79252a6040048e826e085fbed099b942c693a39/eZ/Bundle/EzPublishCoreBundle/ApiLoader/SearchEngineFactory.php#L66
but service is instantiated before site access matching. As result it always created with configuration for default siteaccess. …
> EZP-31701: Marked ezpublish.spi.search_engine as lazy

- eZ/Publish/Core/Helper/FieldsGroups/ArrayTranslatorFieldsGroupsList.php
- eZ/Publish/Core/Helper/FieldsGroups/FieldsGroupsList.php
- eZ/Publish/Core/Helper/Tests/FieldsGroups/ArrayTranslatorFieldsGroupsListTest.php
| **JIRA issue**                          | https://jira.ez.no/browse/EZP-31344
| **Type**                                   | improvement/clean
Complement for:
https://github.com/ezsystems/ezplatform-kernel/pull/73 / https://github.com/ezsystems/ezplatform-content-forms/pull/28
Removed one unused method (after content-forms refactor)
> EZP-31344: Removed one unused method (unused after front refactor)

- eZ/Publish/Core/MVC/Symfony/Security/Tests/UserWrappedTest.php
- eZ/Publish/Core/MVC/Symfony/Security/UserWrapped.php
| **JIRA issue**                          | [EZP-31665](https://jira.ez.no/browse/EZP-31665)
The wrapped apiUser should be serialized as a reference.
> EZP-31665: Serialize WrappedUser::apiUser as a reference.

- eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed.html.twig
- eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed_inline.html.twig
- eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php
- eZ/Publish/Core/MVC/Symfony/View/Tests/Builder/ContentViewBuilderTest.php
| **JIRA issue**                          | [EZP-31595](https://jira.ez.no/browse/EZP-31595)
| **Target eZ Platform version** | v3.0
This PR is a direct continuation of the following PR: https://github.com/ezsystems/ezplatform-kernel/pull/57
The additional parameter has been added to embed views that checks whether the generation of embed Contents' URLs is permitted - if not, the link will not be generated and will be replaced by Content's name.
> EZP-31595: Parametrized embedded Content's URL generation

- eZ/Bundle/EzPublishCoreBundle/ApiLoader/SearchEngineFactory.php
- eZ/Bundle/EzPublishCoreBundle/ApiLoader/SearchEngineIndexerFactory.php
- eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/FieldTypeParameterProviderRegistryPass.php
- eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/QueryTypePass.php
- eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/RegisterSearchEngineIndexerPass.php
- eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/RegisterSearchEnginePass.php
- eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/RegisterSearchEngineIndexerPassTest.php
- eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/RegisterSearchEnginePassTest.php
- eZ/Publish/Core/Base/Container/Compiler/AbstractFieldTypeBasedPass.php
- eZ/Publish/Core/Base/Container/Compiler/Search/FieldRegistryPass.php
- eZ/Publish/Core/Base/Container/Compiler/Storage/ExternalStorageRegistryPass.php
- eZ/Publish/Core/Base/Container/Compiler/Storage/Legacy/FieldValueConverterRegistryPass.php
- eZ/Publish/Core/Base/Container/Compiler/TaggedServiceIdsIterator/BackwardCompatibleIterator.php
- eZ/Publish/Core/Base/Tests/Container/Compiler/TaggedServiceIdsIterator/BackwardCompatibleIteratorTest.php
- eZ/Publish/Core/Base/Tests/Container/Compiler/TaggedServiceIdsIterator/DeprecationErrorCollector.php
- eZ/Publish/Core/settings/search_engines/legacy.yml
| **JIRA issue**                          | [EZP-31588](https://jira.ez.no/browse/EZP-31588)
| **Target eZ Platform version** | `v3.x` 
Tags used to register Search Engine features in the dependency injection container should be consistent and follow Symfony convention (snake case).
Commits between https://github.com/ezsystems/ezplatform-kernel/commit/73ae9f70097be965563c5005bfb7022cf63ac61a - https://github.com/ezsystems/ezplatform-kernel/commit/d0ad33f8caddb031700d0ca9d880d16245 …
> EZP-31588: As a Developer I want to configure search engine features with tags which follows same convention

- bin/.travis/prepare_unittest.sh
| **Target branch**                      | 1.0+
Bumped Solr Bundle to unreleased version `~3.0.3` to force testing on stable branch. Intentionally using tilde to avoid installing the newer tag `v3.1.0` which does not contain required changes.
> [Tests] Bumped Solr Bundle version to test using the latest one

- eZ/Publish/API/Repository/Tests/TrashServiceTest.php
- eZ/Publish/API/Repository/Values/Content/Query/Criterion/LogicalNot.php
- eZ/Publish/API/Repository/Values/Content/Query/Criterion/LogicalOr.php
- eZ/Publish/API/Repository/Values/Content/Query/Criterion/MatchAll.php
- eZ/Publish/API/Repository/Values/Content/Query/Criterion/MatchNone.php
- eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_common.yml
- eZ/Publish/SPI/Repository/Values/Trash/Query/Criterion.php
Allowed the following criteria be used as part of the Trash query:
* `eZ\Publish\API\Repository\Values\Content\Query\Criterion\LogicalNot`
* `eZ\Publish\API\Repository\Values\Content\Query\Criterion\LogicalOr`
* `eZ\Publish\API\Repository\Values\Content\Query\Criterion\MatchAll`
* `eZ\Publish\API\Repository\Values\Content\Query\Criterion\MatchNone`
Follow up for …
> Allowed LogicalOr/LogicalNot/MatchAll/MatchNone criteria be used as part of the Trash query

- composer.json
| **Target eZ Platform version** | `v3.0`+
Merge up of ezsystems/ezpublish-kernel#3049 and adjustment for Symfony 5. Since components are split here, I've manged to narrow it down to `symfony/cache` package, thus setting conflicts with Symfony Cache [5.0.11](https://github.com/symfony/symfony/releases/tag/v5.0.11) and [5.1.3](https://github.com/symfony/symfony/releases/tag/v5.1.3)
> [Composer] Added conflict with Symfony Cache 5.0.11 and 5.1.3

- eZ/Publish/Core/Repository/Strategy/ContentValidator/ContentValidatorStrategy.php
- eZ/Publish/Core/Repository/Tests/ContentValidator/ContentValidatorStrategyTest.php
| **JIRA issue**                          | [EZP-31789](https://jira.ez.no/browse/EZP-31789)
| **BC breaks**                          | yes (this is regression fix)
Unfortunately `array_merge_recursive` reindexes numeric keys and we use numeric field ID as a first level key for field validations errors.
> EZP-31789: Fixed invalid array type returned for getFieldErrors

- eZ/Publish/API/Repository/ObjectStateService.php
- eZ/Publish/API/Repository/Tests/ObjectStateServiceTest.php
- eZ/Publish/Core/Repository/ObjectStateService.php
- eZ/Publish/Core/Repository/SiteAccessAware/ObjectStateService.php
- eZ/Publish/Core/Repository/SiteAccessAware/Tests/ObjectStateServiceTest.php
- eZ/Publish/SPI/Repository/Decorator/ObjectStateServiceDecorator.php
- eZ/Publish/SPI/Repository/Tests/Decorator/ObjectStateServiceDecoratorTest.php
| **JIRA issue**                          | [EZP-29886](https://jira.ez.no/browse/EZP-29886)
Introduced 
* `loadObjectStateGroupByIdentifier(string $objectStateGroupIdentifier, array $prioritizedLanguages = []): ObjectStateGroup` 
* `loadObjectStateByIdentifier(ObjectStateGroup $objectStateGroup, string $objectStateIdentifier, array $prioritizedLanguages = []): ObjectState` 
methods to `\eZ\Publish\API\Repository\ObjectStateService`. 
PR is …
> EZP-29886: Added loadObjectStateGroupByIdentifier/loadObjectStateByIdentifier methods to ObjectStateService

- eZ/Publish/Core/MVC/Symfony/FieldType/ImageAsset/ParameterProvider.php
| **JIRA issue**                          | [EZP-31806](https://jira.ez.no/browse/EZP-31806)
As stated in `\eZ\Publish\Core\FieldType\ImageAsset\Value`
```php
/**
* Related content id's.
*
* @var mixed|null
*/
public $destinationContentId;
```
destination content ID could be also a string, as it is not utilized now and there is always int passed in terms of creating external connectors this needs to be unified in one way or another, till that it …
> EZP-31806: Casted destinationContentId to int

- eZ/Publish/Core/Repository/Helper/RelationProcessor.php
| **JIRA issue**                          | [EZP-31811](https://jira.ez.no/browse/EZP-31811)
| **Target eZ Platform version** | v3.1
Deleted 'Content relation' fieldtype results in an error when editing Content possessing this relation previously. When the relation does not exist anymore `mappedRelations` will be build and throw an exception before.
> EZP-31811: Fixed deleted relation fieldtypes

- eZ/Publish/API/Repository/Values/Content/Query/Criterion/CompositeCriterion.php
We decided to rename `AggregateCriterion` to `CompositeCriterion` during the code review.
> Fixed NotImplementedException exception message thrown by CompositeCriterion::getSpecifications

- eZ/Publish/API/Repository/Tests/BaseTest.php
- eZ/Publish/API/Repository/Tests/FieldType/FloatIntegrationTest.php
- eZ/Publish/Core/FieldType/Float/Type.php
- eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/FloatConverter.php
| **JIRA issue**                          | [EZP-31817](https://jira.ez.no/browse/EZP-31817)
Currently is not possible to search for `ezfloat` values  (e.g. using `\eZ\Publish\API\Repository\Values\Content\Query\Criterion\Field` criterion).
Even if there is `\eZ\Publish\SPI\FieldType\Indexable` implementation registered for `ezfloat` FT (see `\eZ\Publish\Core\FieldType\Float\SearchField`) still …
> EZP-31817: Enabled ezfloat values indexing

- .github/pull_request_template.md
This is a technical PR improving checklist for GitHub Pull Request template, targeted mainly for Community Contributions, so our expectations are more clear.
Changes:
> [DX] Improved GitHub Pull Request template checklist

- eZ/Bundle/EzPublishCoreBundle/Resources/config/helpers.yml
- eZ/Bundle/EzPublishCoreBundle/SiteAccess/Config/ComplexConfigProcessor.php
- eZ/Bundle/EzPublishIOBundle/DependencyInjection/ConfigurationFactory/Flysystem.php
- eZ/Bundle/EzPublishIOBundle/Flysystem/Adapter/SiteAccessAwareLocalAdapter.php
- eZ/Bundle/EzPublishIOBundle/Resources/config/io.yml
- eZ/Bundle/EzPublishIOBundle/Tests/Flysystem/Adapter/SiteAccessAwareLocalAdapterTest.php
- eZ/Publish/SPI/SiteAccess/ConfigProcessor.php
| **JIRA issue**                          | [EZP-31740](https://jira.ez.no/browse/EZP-31740)
| **Required by**                        | ezsystems/ezplatform#596
| **Target eZ Platform version** | `v3.1`+
| **Doc needed**                       | yes, will be covered in meta PR
This PR introduces our custom SiteAccess-aware local NFS adapter based on Flysystem's one. For configuration see the meta PR (ezsystems/ezplatform#596).
We need to be able to process dynamic paths for NFS instance in the form of `%dfs_nfs_path%/$var_dir$/$storage_dir$`, mapped to proper Repository & …
> EZP-31740: Introduced SiteAccess-aware NFS adapter

- eZ/Bundle/PlatformInstallerBundle/src/Command/ValidatePasswordHashesCommand.php
- eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml
- eZ/Publish/API/Repository/Exceptions/PasswordInUnsupportedFormatException.php
- eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php
- eZ/Publish/API/Repository/Tests/UserServiceTest.php
- eZ/Publish/API/Repository/Values/User/User.php
- eZ/Publish/Core/FieldType/Tests/Integration/User/UserStorage/UserDoctrineStorageGatewayTest.php
- eZ/Publish/Core/FieldType/Tests/Integration/User/UserStorage/UserStorageGatewayTest.php
- eZ/Publish/Core/FieldType/Tests/Integration/User/UserStorage/_fixtures/unsupported_hash.yaml
- eZ/Publish/Core/FieldType/Tests/UserTest.php
- eZ/Publish/Core/FieldType/User/Type.php
- eZ/Publish/Core/FieldType/User/UserStorage.php
- eZ/Publish/Core/FieldType/User/UserStorage/Gateway.php
- eZ/Publish/Core/FieldType/User/UserStorage/Gateway/DoctrineStorage.php
- eZ/Publish/Core/MVC/Symfony/Security/Authentication/RepositoryAuthenticationProvider.php
- eZ/Publish/Core/MVC/Symfony/Security/Tests/Authentication/RepositoryAuthenticationProviderTest.php
- eZ/Publish/Core/Repository/User/Exception/UnsupportedPasswordHashType.php
- eZ/Publish/Core/Repository/User/PasswordHashService.php
| **JIRA issue**                          | [EZP-31462](https://jira.ez.no/browse/EZP-31462)
| **Required by**                       | ezsystems/ezplatform-user#75 ezsystems/ezplatform#593
In order to have better UX, there was added redirection to 'Change password' page in a case when a user with unsupported hash type tries to log in. To achieve that more significant exceptions were added to detect unsupported hash type scenario - an exception …
> EZP-31462: Added command checking if there are any unsupported password hash types

- eZ/Bundle/EzPublishIOBundle/Migration/FileLister/FileRowReader/LegacyStorageFileRowReader.php
| **JIRA issue**                          | [EZP-31748](https://jira.ez.no/browse/EZP-31748)
| **Target eZ Platform version** | `v3.0.5`, `v3.1.0`
In some cases `ezplatform:io:migrate-files` command fails because of the following error:
```bash
bin/console ezplatform:io:migrate-files --from=default,default --to=XXX,YYY --no-interaction -vvv
...
In LegacyStorageFileRowReader.php line 45:
[ErrorException] 
Notice: Trying to access array offset on value of type bool
```
> LegacyStorageFileRowReader: handle the case when statement->fetch returns false

- eZ/Bundle/EzPublishIOBundle/Tests/DependencyInjection/EzPublishIOExtensionTest.php
- eZ/Bundle/EzPublishIOBundle/Tests/_fixtures/url_prefix_test_config.yaml
- eZ/Publish/Core/IO/Tests/UrlDecorator/AbsolutePrefixTest.php
- eZ/Publish/Core/IO/UrlDecorator/AbsolutePrefix.php
| **JIRA issue**                          | EZP-31912
| **Target eZ Platform version** | `v3.1`+
| **Doc needed**                       | ezsystems/developer-documentation#1142
This PR fixes [decorating binary files (images, other media) URLs with custom `url_prefix`](https://doc.ezplatform.com/en/3.1/guide/file_management/#using-a-static-server-for-images).
While the JIRA ticket describes complicated AWS case, in fact URL prefix can be used with local (default) binary handler and it was the part which was broken.
In 2.5 [we used to fetch `io.url_prefix` from dynamic …
> EZP-31912: Fixed decorating binary files URLs with proper absolute prefix

- eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
- eZ/Publish/Core/MVC/Symfony/Event/ResolveRenderOptionsEvent.php
- eZ/Publish/Core/MVC/Symfony/Templating/Exception/InvalidResponseException.php
- eZ/Publish/Core/MVC/Symfony/Templating/RenderContentStrategy.php
- eZ/Publish/Core/MVC/Symfony/Templating/RenderLocationStrategy.php
- eZ/Publish/Core/MVC/Symfony/Templating/RenderMethod/RenderEdgeSideInclude.php
- eZ/Publish/Core/MVC/Symfony/Templating/RenderMethod/RenderInline.php
- eZ/Publish/Core/MVC/Symfony/Templating/RenderMethod/RenderSubRequest.php
- eZ/Publish/Core/MVC/Symfony/Templating/RenderOptions.php
- eZ/Publish/Core/MVC/Symfony/Templating/RenderStrategy.php
- eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/RenderContentExtension.php
- eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/RenderExtension.php
- eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/RenderLocationExtension.php
- eZ/Publish/SPI/MVC/Templating/BaseRenderStrategy.php
- eZ/Publish/SPI/MVC/Templating/RenderMethod.php
- eZ/Publish/SPI/MVC/Templating/RenderMethod/ControllerRenderMethod.php
- eZ/Publish/SPI/MVC/Templating/RenderStrategy.php
- eZ/Publish/SPI/Options/MutableOptionsBag.php
- eZ/Publish/SPI/Options/OptionsBag.php
| **JIRA issue**                          | EZP-31851
Based on a Proof of Concept/Experiment: https://github.com/ezsystems/ezpublish-kernel/pull/1518
This PR provides two Twig helper functions and extensibility point for more:
- `ez_render_content` - abstracts Content rendering via different rendering methods (default `inline`, `subrequest`, `esi`)
- `ez_render_location` - abstracts Location rendering via different rendering methods (default `inline`, `subrequest`, `esi`)
- `ez_render` - …
> EZP-31851: Added Twig helpers that abstracts content rendering

- eZ/Publish/Core/MVC/Symfony/Security/Authentication/RememberMeRepositoryAuthenticationProvider.php
| **JIRA issue**                          | EZP-31773
| **Backported from**                 | `dev-master` (`1.2.x-dev`) PR #91
This is a cherry-pick for 1.1 (eZ Platform 3.1.x) for #91
- ~Tests are implemented.~ // n/a cherry-pick (though probably they would be useful)
> EZP-31773: Backported the fix for multiple user providers support

- eZ/Publish/Core/MVC/Symfony/Templating/RenderContentStrategy.php
- eZ/Publish/Core/MVC/Symfony/Templating/RenderLocationStrategy.php
- eZ/Publish/Core/MVC/Symfony/Templating/Tests/BaseRenderStrategyTest.php
- eZ/Publish/Core/MVC/Symfony/Templating/Tests/RenderContentStrategyTest.php
- eZ/Publish/Core/MVC/Symfony/Templating/Tests/RenderLocationStrategyTest.php
- eZ/Publish/Core/MVC/Symfony/Templating/Tests/RenderOptionsTest.php
- eZ/Publish/Core/MVC/Symfony/Templating/Tests/RenderStrategyTest.php
| **JIRA issue**                          | EZP-31851
| **Type**                                   | feature/bug/improvement
| **Target eZ Platform version** | `v3.2` - please update `x` accordingly
Missing tests.
Also fixes wrong getter scope resulting in `null` value for header.
> EZP-31851: Added Unit tests for Render strategies

- eZ/Publish/API/Repository/Tests/Values/Content/Query/Aggregation/RangeTest.php
| **Doc needed**                       |  no
Fixed invalid namespace in RangeTest:  `Values\Content\Query\Aggregatio` => `eZ\Publish\API\Repository\Tests\Values\Content\Query\Aggregation`
> Fixed RangeTest namespace

- eZ/Publish/API/Repository/Tests/UserServiceTest.php
Added +/- 2s error margin when asserting  $passwordUpdatedAt in the UserServiceTest::testUpdateUserUpdatesExpectedProperties in order to avoid the following false negatives in CI builds.
```
There was 1 failure:
1) eZ\Publish\API\Repository\Tests\UserServiceTest::testUpdateUserUpdatesExpectedProperties
Failed asserting that 1603055825 is equal to 1603055826 or is greater than 1603055826.
/home/travis/build/ezsystems/ezplatform-kernel/eZ/Publish/API/R …
```
> Add +/- 2s error margin for $passwordUpdatedAt in the UserServiceTest::testUpdateUserUpdatesExpectedProperties

- eZ/Publish/API/Repository/Tests/SearchServiceAggregationTest.php
- eZ/Publish/Core/FieldType/Author/SearchField.php
| Question | Answer |
| --- | --- |
| **JIRA issue** | EZP-32045 |
| **Type** | feature |
| **Target eZ Platform version** | `v3.2` |
| **BC breaks** | no |
| **Doc needed** | yes |
Added support for `\eZ\Publish\API\Repository\Values\Content\Query\Aggregation\Field\AuthorTermAggregation`. Usage is exact the same as in case of other field based aggregations:
```php
$query = new Query();
$query->aggregations[] = new AuthorTermAggregation('group_by_author', 'article', 'author');
```
The result of the aggregation is `\eZ\Publish\API\Repository\Values\Content\Search\AggregationResult\TermAggregationResult`. Key of `\eZ\Publish\API\Repository\Values\Content\Search\AggregationResult\TermAggregationResultEntry` is `\eZ\Publish\Core\FieldType\Author\Author`.
```php
$results = …
```
> EZP-32045: Added support for AuthorTermAggregation

- eZ/Publish/API/Repository/Tests/SearchServiceAggregationTest.php
- eZ/Publish/API/Repository/Tests/Values/Content/Query/Aggregation/Location/SubtreeTermAggregationTest.php
- eZ/Publish/API/Repository/Values/Content/Query/Aggregation/Location/SubtreeTermAggregation.php
| **JIRA issue**                          | EZP-32045
Added support for SubtreeTermAggregation
> EZP-32045: Added support for SubtreeTermAggregation

- eZ/Bundle/EzPublishCoreBundle/Resources/config/sort_spec.yml
- eZ/Publish/API/Repository/Tests/SearchService/SortClause/ScoreTest.php
- eZ/Publish/API/Repository/Values/Content/Query/SortClause/Score.php
| **JIRA issue**                          | EZP-32107
| **Target eZ Platform version** | `v3.3` 
Added `\eZ\Publish\API\Repository\Values\Content\Query\SortClause\Score` which allows explicitly define sorting by relevance score. Typical use case for  `\eZ\Publish\API\Repository\Values\Content\Query\SortClause\Score` is composition of multiple sort clauses: 
```php
$query = new Query([
'query' => new Criterion\FullText('foo'),
'sortClauses' => [
new SortClause\Score(Query::SORT_DESC),
// Sort results alphabetically in case of equal …
```
> EZP-32107: Added Score sort clause

- eZ/Publish/Core/Pagination/Pagerfanta/ContentFilteringAdapter.php
- eZ/Publish/Core/Pagination/Pagerfanta/LocationFilteringAdapter.php
- eZ/Publish/Core/Pagination/Tests/ContentFilteringAdapterTest.php
- eZ/Publish/Core/Pagination/Tests/LocationFilteringAdapterTest.php
| **JIRA issue**                          | EZP-32151
Impl. Pagerfanta adapters for Repository Filtering API.
> EZP-32151: Added Pagerfanta adapters for Repository Filtering API

- eZ/Publish/Core/FieldType/ImageAsset/ImageAssetThumbnailStrategy.php
| **JIRA issue**                          | EZP-32128
This not fix _exactly_ issue described in jira ticket, but as steps to reproduce are that same and int affects similar scope I solved both of issues at that same time. As this refers to failure with obtaining content thumbnail it also affects `3.1` (in opposition to https://github.com/ezsystems/ezplatform-rest/pull/59)
> EZP-32128: Thumbnails are no longer generated for removed image asset relation

- eZ/Publish/Core/MVC/Symfony/Component/Serializer/SerializerTrait.php
| **JIRA issue**                          | EZEE-3356
| **Related PR**                       | https://github.com/ezsystems/ezplatform-site-factory/pull/100
JsonSerializableNormalizer needs to be added to deal with objects implementing the JsonSerializable interface.
> EZEE-3356: Added JsonSerializableNormalizer for Serializer to handle Serializable interface

- eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/BinaryLoaderTest.php
- eZ/Publish/Core/MVC/Symfony/Security/Tests/Authentication/RememberMeRepositoryAuthenticationProviderTest.php
| **JIRA issue**                          | None
Fixes tests breaking after Symfony 5.2 release.
> Fixed tests after Symfony 5.2 release

- eZ/Publish/Core/FieldType/BinaryBase/PathGenerator/LegacyPathGenerator.php
| **JIRA issue**                          | EZP-32031
| **Target eZ Platform version** | master
LegacyPathGenerator uses a less than ideal way of generating unpredictable filenames:
https://github.com/ezsystems/ezplatform-kernel/blob/c1750540a0adf09b3242266fc32937bdcc3424fe/eZ/Publish/Core/FieldType/BinaryBase/PathGenerator/LegacyPathGenerator.php#L20
It's an md5 hash of a uniqid prefixed by a microtime float. Code scanners report the md5 usage as a potential security vulnerability. It isn't in this case, but the whole …
> EZP-32031: Better BinaryBase filename generation

- eZ/Bundle/EzPublishCoreBundle/Resources/config/sort_spec.yml
- eZ/Publish/API/Repository/Tests/BaseTest.php
- eZ/Publish/API/Repository/Tests/SearchServiceTest.php
- eZ/Publish/API/Repository/Values/Content/Query/SortClause/CustomField.php
- eZ/Publish/API/Repository/Values/Content/Query/SortClause/Target/CustomFieldTarget.php
- eZ/Publish/Core/QueryType/BuiltIn/SortSpec/SortClauseParser/CustomFieldSortClauseParser.php
- eZ/Publish/Core/QueryType/BuiltIn/SortSpec/SortSpecParser.php
- eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Tests/SortClauseParser/CustomFieldSortClauseParserTest.php
| **JIRA issue**                          | EZP-32108
| **Related PRs**                      | https://github.com/ezsystems/ezplatform-elastic-search-engine/pull/23 <br /> https://github.com/ezsystems/ezplatform-solr-search-engine/pull/204 |
Added `\eZ\Publish\API\Repository\Values\Content\Query\SortClause\CustomField` which allows sort search results using raw search index field. 
```php
$query = new Query([
'query' => new Criterion\MatchAll(),
'sortClauses' => [
new …
```
> EZP-32108: Added CustomField sort clause

- eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php
| **JIRA issue**                          | EZP-32184
| **Target eZ Platform version** | `v3.1`, `v3.2`
Excerpt from JIRA:
>Under several circumstances (https://doc.ibexa.co/en/3.1/guide/performance/#reducing-memory-usage) there might be potential memory leaks while running ezplatform:reindex command against big databases. The idea is to put a proper warning explaining several of them.
> EZP-32184: Added warning about possible memory leaks for reindex command

- eZ/Bundle/EzPublishCoreBundle/Resources/config/sort_spec.yml
- eZ/Publish/API/Repository/Tests/BaseTest.php
- eZ/Publish/API/Repository/Tests/SearchService/SortClause/AbstractSortClauseTest.php
- eZ/Publish/API/Repository/Tests/SearchService/SortClause/ContentTranslatedNameTest.php
- eZ/Publish/API/Repository/Tests/SearchService/SortClause/ScoreTest.php
- eZ/Publish/API/Repository/Values/Content/Query/SortClause/ContentTranslatedName.php
| **JIRA issue**                          | EZP-32111
Added `\eZ\Publish\API\Repository\Values\Content\Query\SortClause\ContentTranslatedName` which allows sort search results using translated content name
```php
$query = new Query([
'query' => new Criterion\MatchAll(),
'sortClauses' => [
new SortClause\ContentTranslatedName(),
],
]);
```
> EZP-32111: Added ContentTranslatedName sort clause

- eZ/Publish/API/Repository/Tests/ContentServiceTest.php
- eZ/Publish/Core/Repository/ContentService.php
| **JIRA issue**                          | EZP-32219
| **Target eZ Platform version** | v3.2
**Steps to reproduce:**
1. Create new ContentType i.e. "News".
2. Add a single Textline field i.e. "Title".
3. Set "Sort children by default by" to "Location priority"
4. Set "Sort children by default in order" to "Descending".
5. Create new News content anywhere.
6. Observe Sub-items sorting order in the Details tab for this content.
**Expected result:**
Sub-items sorting for new content should have the same value as one that has been set in …
> EZP-32219: Fix ContentType sorting defaults has no effect on new created objects

- eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
- eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
| **JIRA issue**                          | EZP-32214
| **Target eZ Platform version** | `v3.3` - please update `x` accordingly
Since we are using ENV variables to setup HTTP Cache purge driver, it's needed to resolve all envs at compile time. This is rather bad solution because ENVs are not designed to be used this way. In order to make it work we need to call `Container::resolveEnvPlaceholders` to get real values. Previously it was working because `config/packages/overrides/*.php` files were used and they resolved values …
> EZP-32214: Made purge type configuration using env vars resolvable at compile time

- eZ/Publish/API/Repository/Tests/UserServiceAuthorizationTest.php
- eZ/Publish/API/Repository/Tests/UserServiceTest.php
- eZ/Publish/API/Repository/UserService.php
- eZ/Publish/Core/Repository/SiteAccessAware/Tests/UserServiceTest.php
- eZ/Publish/Core/Repository/SiteAccessAware/UserService.php
- eZ/Publish/Core/Repository/UserService.php
- eZ/Publish/SPI/Repository/Decorator/UserServiceDecorator.php
- eZ/Publish/SPI/Repository/Tests/Decorator/UserServiceDecoratorTest.php
| **JIRA issue**                          | EZP-32247
Introduced `\eZ\Publish\API\Repository\UserService::loadUserGroupByRemoteId`.
> EZP-32247: As a Developer I want load user group by remote id

- eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
- eZ/Bundle/PlatformInstallerBundle/src/Command/ValidatePasswordHashesCommand.php
- eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml
- eZ/Publish/API/Repository/PasswordHashService.php
- eZ/Publish/API/Repository/Values/User/User.php
- eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
- eZ/Publish/Core/FieldType/Tests/Integration/User/UserStorage/UserStorageGatewayTest.php
- eZ/Publish/Core/FieldType/Tests/UserTest.php
- eZ/Publish/Core/FieldType/User/Type.php
- eZ/Publish/Core/FieldType/User/UserStorage.php
- eZ/Publish/Core/FieldType/User/UserStorage/Gateway.php
- eZ/Publish/Core/FieldType/User/UserStorage/Gateway/DoctrineStorage.php
- eZ/Publish/Core/Repository/Repository.php
- eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
- eZ/Publish/Core/Repository/Tests/Service/Mock/UserTest.php
- eZ/Publish/Core/Repository/Tests/User/PasswordHashServiceTest.php
- eZ/Publish/Core/Repository/User/PasswordHashService.php
- eZ/Publish/Core/Repository/User/PasswordHashServiceInterface.php
- eZ/Publish/Core/Repository/UserService.php
- eZ/Publish/Core/settings/fieldtype_services.yml
- eZ/Publish/Core/settings/fieldtypes.yml
- eZ/Publish/SPI/Tests/FieldType/UserIntegrationTest.php
| **JIRA issue**                          | EZP-32250
Added methods
* `getSupportedHashTypes(): array`
* `isHashTypeSupported(int $hashType): bool`
to `\eZ\Publish\Core\Repository\User\PasswordHashServiceInterface` and refactor existing `\eZ\Publish\API\Repository\Values\User\User::SUPPORTED_PASSWORD_HASHES` usages
This allows to decorate `PasswordHashService` in 3rd-party bundles and add support for custom password hash types.
> EZP-32250: Exposed PasswordHashService APIs

- eZ/Bundle/EzPublishCoreBundle/Features/QueryController/query_controller.feature
- eZ/Publish/Core/MVC/Symfony/Controller/Content/QueryController.php
- eZ/Publish/Core/MVC/Symfony/Controller/QueryRenderController.php
- eZ/Publish/Core/MVC/Symfony/Controller/Tests/QueryRenderControllerTest.php
- eZ/Publish/Core/Pagination/Pagerfanta/AbstractSearchResultAdapter.php
- eZ/Publish/Core/Pagination/Pagerfanta/AdapterFactory/SearchHitAdapterFactory.php
- eZ/Publish/Core/Pagination/Pagerfanta/ContentSearchHitAdapter.php
- eZ/Publish/Core/Pagination/Pagerfanta/FixedSearchResultHitAdapter.php
- eZ/Publish/Core/Pagination/Pagerfanta/LocationSearchHitAdapter.php
- eZ/Publish/Core/Pagination/Pagerfanta/Pagerfanta.php
- eZ/Publish/Core/Pagination/Pagerfanta/SearchResultAdapter.php
- eZ/Publish/Core/Pagination/Tests/AdapterFactory/SearchHitAdapterFactoryTest.php
- eZ/Publish/Core/Pagination/Tests/ContentSearchHitAdapterTest.php
- eZ/Publish/Core/Pagination/Tests/FixedSearchResultHitAdapterTest.php
- eZ/Publish/Core/Pagination/Tests/LocationSearchAdapterTest.php
- eZ/Publish/Core/Pagination/Tests/LocationSearchHitAdapterTest.php
- eZ/Publish/Core/Pagination/Tests/PagerfantaTest.php
| Question | Answer |
| --- | --- |
| **JIRA issue** | EZP-32110 |
| **Type** | feature |
| **Target eZ Platform version** | `v3.3` |
| **BC breaks** | no |
| **Doc needed** | yes |
Introduced `\eZ\Publish\Core\Pagination\Pagerfanta\SearchResultAdapter`
```php
/**
* Contract for \eZ\Publish\API\Repository\SearchService based adapters.
*/
interface SearchResultAdapter extends AdapterInterface
{
/**
* Get results of aggregations associated with search query.
*
* Generates addition query if called before AdapterInterface::getSlice or AdapterInterface::getNbResults.
*/
public function getAggregations(): AggregationResultCollection;
/**
* Get the duration of the search processing for current results slice (in s).
*
* Returns null if called before AdapterInterface::getSlice.
*/
public function …
```
> EZP-32110: Exposed more search result data from Pagefanta adapters

- eZ/Publish/Core/Limitation/SiteAccessLimitationType.php
- eZ/Publish/Core/Limitation/Tests/SiteAccessLimitationTypeTest.php
| **JIRA issue**                          | EZP-32181
This PR exposes currently internal `eZ\Publish\Core\Limitation\SiteAccessLimitationType::generateSiteAccessValue`.
It is needed for tools like ezmigration, which duplicates the implementation in places where mapping between value stored in persistence is needed to be mapped to an existing SiteAccess.
> EZP-32181: Exposed Site Access Limitation type persistence value generation

- eZ/Bundle/EzPublishCoreBundle/Imagine/ImageAsset/AliasGenerator.php
| **Target eZ Platform version** | `v3.3.X` 
| **BC breaks**                          |no
| **Doc needed**                       |no
This PR provides fix for ImageAsset/AliasGenerator::getVariation. Argument contentId in ContentService::loadContent expects to be int but string given when try to get content for imageasset
> Fixed cast to int destinationContentId in ImageAsset/AliasGenerator

- eZ/Bundle/EzPublishIOBundle/Resources/config/io.yml
| **JIRA issue**                          | EZP-32255
| **BC breaks**                          | maybe
Due to how are configurations loaded with Flex, we have to move configuration to where it is overwritten (EzPlatformCoreBundle).
> EZP-32255: Get rid of default DSF configuration (moved to Core)

- eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/full.html.twig
| **JIRA issue**                          | [https://jira.ez.no/browse/EZP-31659](https://jira.ez.no/browse/EZP-31659)
Adds the location as a parameter to `ez_render_field()` in the default view template. Required by the query fieldtype's handling of locations (https://github.com/ezsystems/ezplatform-query-fieldtype/pull/38).
> Added the location parameter to ez_render_field

- eZ/Publish/Core/FieldType/Image/ImageThumbnailStrategy.php
- eZ/Publish/Core/FieldType/ImageAsset/ImageAssetThumbnailStrategy.php
- eZ/Publish/Core/Repository/Mapper/ContentDomainMapper.php
- eZ/Publish/Core/Repository/Strategy/ContentThumbnail/Field/ContentFieldStrategy.php
- eZ/Publish/Core/Repository/Strategy/ContentThumbnail/FirstMatchingFieldStrategy.php
- eZ/Publish/Core/Repository/Strategy/ContentThumbnail/StaticStrategy.php
- eZ/Publish/Core/Repository/Strategy/ContentThumbnail/ThumbnailChainStrategy.php
- eZ/Publish/Core/Repository/Tests/ContentThumbnail/ContentFieldStrategyTest.php
- eZ/Publish/Core/settings/tests/integration_legacy.yml
- eZ/Publish/Core/settings/thumbnails.yml
- eZ/Publish/SPI/Repository/Strategy/ContentThumbnail/Field/ThumbnailStrategy.php
- eZ/Publish/SPI/Repository/Strategy/ContentThumbnail/ThumbnailStrategy.php
| **JIRA issue**                          | EZP-31795
https://github.com/ezsystems/ezplatform-admin-ui/pull/1690
https://github.com/ezsystems/ezplatform-connector-dam/pull/29
> EZP-31795: Added VersionInfo to getThumbnail method in order to utilise builtin caching mechanism

- eZ/Bundle/EzPublishCoreBundle/Cache/Warmer/ProxyCacheWarmer.php
- eZ/Bundle/EzPublishCoreBundle/Resources/config/thumbnails.yml
- eZ/Publish/Core/FieldType/Image/ImageThumbnailProxyStrategy.php
- eZ/Publish/Core/settings/thumbnails.yml
| **JIRA issue**                          | EZP-31795
> EZP-31795: Introduced proxy objects for content thumbnails

- eZ/Bundle/EzPublishCoreBundle/EventListener/IndexRequestListener.php
- eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/IndexRequestListenerTest.php
| **JIRA issue**                          | EZP-32281
| **Target eZ Platform version** | v3.1
`IndexRequestListener` originally had `needsForward` set to `true` which later on resulted in `needsCaseRedirect` in `UrlAliasRouter` returning `false` as both paths were the same which finally resulted in redirect not being fired. That shouldn't be the case and the redirect should occur at an earlier stage without the unnecessary forward.
> EZP-32281: IndexRequestListener requires redirect

- composer.json
| **Target eZ Platform version** | `v3.2`+
Our MVC Controller still relies on the deprecated `symfony/templating`, however we didn't have it in our dependencies. Looks like it was installed as a peer dependency of Liip Imagine Bundle, so the issue wasn't discovered. With the today's release of Liip Imagine Bundle 2.5.0 that dependency is gone, so we need to (and should prior to that anyway) require it explicitly. 
Both test and production code (a bit implicitly) rely on that, so putting it in the `require` section.
Observed CI failure …
> [Composer] Added missing dependency on symfony/templating

- eZ/Publish/API/Repository/Tests/UserServiceTest.php
- eZ/Publish/Core/Repository/User/PasswordHashServiceInterface.php
- eZ/Publish/Core/Repository/UserService.php
| **JIRA issue**                          | EZP-31462
| **Target eZ Platform version** | `v3.2`+
The previous fixes are incomplete. When an invalid hash type is detected, we expire the password and ask the user to enter a new password. But when we save this new password, we don't update the hash type, which means the password isn't saved, and the user ends up in a redirect loop.
However, cache can mask the issue. If you test by manually changing hash type to an invalid one in the db, you have to clear caches before you go through the …
> EZP-31462: Removed password hash types break login

- bootstrap.php
- composer.json
- eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/OriginalRequestListenerTest.php
- eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/RequestEventListenerTest.php
- phpunit-integration-legacy-solr.xml
- phpunit-integration-legacy.xml
- phpunit.xml
| **JIRA issue**                          | EZP-32384
| **Target eZ Platform version** | `v3.2` 
https://github.com/symfony/symfony/pull/40043
> EZP-32384: Fixed time depended tests

- eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php
- eZ/Bundle/EzPublishCoreBundle/Resources/config/commands.yml
- eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
| **JIRA issue**                          | [IBX-143](https://issues.ibexa.co/browse/IBX-143)
| **Target Ibexa version** | `v3.3`+
| **Tests pass**              | yes, failure is unrelated
This PR aligns a merge up of ezsystems/ezpublish-kernel#3094 changes with master.
All commands are defined in `eZ/Bundle/EzPublishCoreBundle/Resources/config/commands.yml`, so the old definition was removed from `eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml`. 
Moreover the command can't be lazy as it seems not compatible with `BackwardCompatibleCommand` feature (making both …
> IBX-143: Fixed merge-up of reindex command changes

- .github/workflows/release.yml
- eZ/Publish/Core/FieldType/BinaryBase/BinaryBaseStorage.php
- eZ/Publish/Core/FieldType/BinaryBase/Type.php
- eZ/Publish/Core/FieldType/BinaryFile/Type.php
- eZ/Publish/Core/FieldType/Media/Type.php
- eZ/Publish/Core/FieldType/Tests/BinaryFileTest.php
- eZ/Publish/Core/MVC/Symfony/FieldType/BinaryBase/ContentDownloadUrlGenerator.php
- eZ/Publish/Core/settings/fieldtypes.yml
- eZ/Publish/SPI/FieldType/BinaryBase/PathGenerator.php
- eZ/Publish/SPI/FieldType/BinaryBase/PathGeneratorInterface.php
- eZ/Publish/SPI/FieldType/BinaryBase/RouteAwarePathGenerator.php
| **JIRA issue**                          | [IBX-85](https://issues.ibexa.co/browse/IBX-85)
| **Target eZ Platform version** | `v3.3` & `2.5`
Merge up for https://github.com/ezsystems/ezpublish-kernel/pull/3096
> This fixes the issue of Content sharing field with Site-Access aware/reliant external data.
> 
> The root of the issue is that "uri" for `BinaryFileField` is calculated right after it is acquired from the database, in SPI persistence layer. This causes cache to contain this calculated "uri" value in all SiteAccess' that share …
> IBX-85: Fixed Content cache containing invalid "uri" for file field types

- eZ/Publish/API/Repository/Tests/FieldType/DateIntegrationTest.php
- eZ/Publish/Core/FieldType/Date/Type.php
- eZ/Publish/Core/FieldType/Date/Value.php
- eZ/Publish/Core/FieldType/Tests/DateTest.php
| **JIRA issue**                          | [IBX-300](https://issues.ibexa.co/browse/IBX-300)
Related PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/1752
> IBX-300: Added timezone offset to timestamp

- eZ/Publish/API/Repository/Tests/BaseURLServiceTest.php
- eZ/Publish/API/Repository/Tests/URLServiceTest.php
- eZ/Publish/API/Repository/Values/URL/SearchResult.php
- eZ/Publish/API/Repository/Values/URL/URLQuery.php
- eZ/Publish/Core/FieldType/Tests/Url/Gateway/DoctrineStorageTest.php
- eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/DoctrineStorage.php
- eZ/Publish/Core/Persistence/Legacy/Tests/URL/Gateway/DoctrineDatabaseTest.php
- eZ/Publish/Core/Persistence/Legacy/Tests/URL/Gateway/_fixtures/urls.php
- eZ/Publish/Core/Persistence/Legacy/Tests/URL/HandlerTest.php
- eZ/Publish/Core/Persistence/Legacy/URL/Gateway.php
- eZ/Publish/Core/Persistence/Legacy/URL/Gateway/DoctrineDatabase.php
- eZ/Publish/Core/Persistence/Legacy/URL/Handler.php
| **JIRA issue**                          | [IBX-340](https://issues.ibexa.co/browse/IBX-340)
Prevent multiple database `count` queries when paginating URL lists.
Without the patch:
With the patch:
> IBX-340: Allowed URL Gateway queries to not perform count operations

- eZ/Publish/Core/FieldType/Date/SearchField.php
| **JIRA issue**                          | [IBX-300](https://issues.ibexa.co/browse/IBX-300)
| **Target eZ Platform version** | `v3.2`, `v3.3`
After merged up to the master, appeared a problem with the test SOLR, so I changed the searchField class to using timezone like another place with a date field
> IBX-300 changed search field data to using timezone for timestamp

- eZ/Publish/API/Repository/Tests/SearchService/Aggregation/Field/DateRangeAggregationTest.php
| **JIRA issue**                          | [IBX-415](https://issues.ibexa.co/browse/IBX-415)
| **Target eZ Platform version** | `v3.2+` 
I ran locally tests for SOLR on `eZ/Publish/API/Repository/Tests/SearchService/` dir with different time zones and all of them passed
Also, I restarted the test for SOLR in Travis 4-5 times and always test passed
> removed timezone for ezdate field from tests

- eZ/Publish/API/Repository/Values/Content/Query/Criterion.php
| **JIRA issue**                          | N/A
Fixed phpdoc declaration for `Criterion` to match it's actual usage.
This will prevent PHPStan errors reported by invalid criterion usage from popping up in dependent packages.
> Fixed Criterion phpdoc mismatch

- eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
- eZ/Publish/Core/settings/tests/common.yml
| **Target eZ Platform version** | `v4.x`
Added `eZ\Publish\Core\MVC\Symfony\SiteAccess\SiteAccessServiceInterface` service definition
```yaml
eZ\Publish\Core\MVC\Symfony\SiteAccess\SiteAccessServiceInterface:
alias: 'ezpublish.siteaccess_service'
```
for the needs of autowiring.
> Allow to autowire eZ\Publish\Core\MVC\Symfony\SiteAccess\SiteAccessServiceInterface

- eZ/Publish/Core/settings/storage_engines/common.yml
| **JIRA issue**                          | [IBX-546](https://issues.ibexa.co/browse/IBX-546)
Adds `TransactionHandler` interface alias / autowiring service alias.
> IBX-546: Added missing TransactionHandler interface service alias

- eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/BinaryLoaderTest.php
| **Target Ibexa version** | `v3.2` only
Looks like a83c3ec for Symfony 5.2 was applied by accident on the Kernel branch 1.2 which supports Symfony 5.1.x.
See [failing nightly build](https://travis-ci.com/github/ezsystems/ezplatform-kernel/jobs/513313519#L1279).
To be restored on the merge up.
> [Tests] Aligned BinaryLoaderTest with symfony/mime 5.1.x

- eZ/Publish/Core/Helper/FieldsGroups/ArrayTranslatorFieldsGroupsList.php
| **JIRA issue**                          | EZP-31859
Given, groups are translated in the constructor, the proper locale setting doesn't kick in which results in no translations being picked up from the defined translator domain. Moved it to the `getGroups` method is enough to have it translated at the moment of fetching.
Also, I will create a doc PR once this solution is approved, to mention that changing BO language is necessary to have group names translated accordingly, ref: …
> EZP-31859: Fixed field group names being not translated

- eZ/Bundle/EzPublishCoreBundle/Converter/RepositoryParamConverter.php
| **JIRA issue**                          | [IBX-527](https://issues.ibexa.co/browse/IBX-527) (depends on this for static analysis)
| **BC breaks**                          | no, phpdoc only
`eZ\Bundle\EzPublishCoreBundle\Converter\ContentParamConverter` & `eZ\Bundle\EzPublishCoreBundle\Converter\LocationParamConverter` (descendants) both return `ValueObject`s, not strings.
New `CustomerGroupParamConverter` will also return a `ValueObject`.
> IBX-527: Fixed phpdoc return type mismatch in RepositoryParamConverter

- eZ/Publish/Core/Persistence/Cache/LocationHandler.php
Merge up PR for https://github.com/ezsystems/ezpublish-kernel/pull/3109
> IBX-610: Implemented InMemory cache for remaining LocationHandler methods

- eZ/Publish/SPI/FieldType/GatewayBasedStorage.php
| **JIRA issue**                          | N/A
Adds `@template` annotation with corresponding `phpstan-param` (for `__construct`) & `phpstan-var` (for property) that will allow static analysis of extending classes to pass when annotated:
```php
/**
* @extends \eZ\Publish\SPI\FieldType\GatewayBasedStorage<
*     StorageGateway
* >
*/
final class Storage extends GatewayBasedStorage
{
}
```
See https://phpstan.org/blog/generics-in-php-using-phpdocs
> Added generic template annotation for static analysis

- eZ/Publish/API/Repository/Tests/SettingServiceTest.php
- eZ/Publish/Core/Repository/SettingService.php
| **JIRA issue**                          | IBX-688
| **Doc needed**                       | ?
Setting value representation should not be changed when loading it from persistence.
> IBX-688: SettingService::buildSettingDomainObject deserialize hashes as stdClass

- eZ/Publish/API/Repository/Tests/Values/Filter/FilterTest.php
- eZ/Publish/API/Repository/Values/Filter/Filter.php
| **Type**                                   | i
| **Doc needed**                       | ?
Added `withOffset` and `withLimit` metods to `\eZ\Publish\API\Repository\Values\Filter\Filter`. 
Primary use case is batch processing using Filtering API. In such scenario limit (batch size) is set at the beginning of data processing and only offset (data pointer) is changing over iteration. 
Currently with `\eZ\Publish\API\Repository\Values\Filter\Filter::sliceBy(...)`  developer is forced to set both limit and offset at once.
> Added \eZ\Publish\API\Repository\Values\Filter\Filter::{withOffset,withLimit} methods

- eZ/Publish/API/Repository/Iterator/BatchIterator.php
- eZ/Publish/API/Repository/Iterator/BatchIteratorAdapter.php
- eZ/Publish/API/Repository/Iterator/BatchIteratorAdapter/AbstractSearchAdapter.php
- eZ/Publish/API/Repository/Iterator/BatchIteratorAdapter/ContentFilteringAdapter.php
- eZ/Publish/API/Repository/Iterator/BatchIteratorAdapter/ContentInfoSearchAdapter.php
- eZ/Publish/API/Repository/Iterator/BatchIteratorAdapter/ContentSearchAdapter.php
- eZ/Publish/API/Repository/Iterator/BatchIteratorAdapter/LocationFilteringAdapter.php
- eZ/Publish/API/Repository/Iterator/BatchIteratorAdapter/LocationSearchAdapter.php
- eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorAdapter/AbstractSearchAdapterTest.php
- eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorAdapter/ContentFilteringAdapterTest.php
- eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorAdapter/ContentInfoSearchAdapterTest.php
- eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorAdapter/ContentSearchAdapterTest.php
- eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorAdapter/LocationFilteringAdapterTest.php
- eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorAdapter/LocationSearchAdapterTest.php
- eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorTest.php
- eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorTestAdapter.php
- eZ/Publish/API/Repository/Values/Content/Search/SearchResult.php
| **JIRA issue**                          | https://issues.ibexa.co/browse/IBX-719
`BatchIterator`  allows iterate over result sets (e.g. content objects, locations) which cannot be loaded into memory at once.
Examples from existing code base:
https://github.com/ezsystems/ezplatform-kernel/blob/4c840747ef4a75782becc7dac987ff615775d242/eZ/Bundle/EzPublishCoreBundle/Command/CheckURLsCommand.php#L90-L108
https://github.com/ezsystems/ezplatform-kernel/blob/4c840747ef4a75782becc7dac987ff615775d2 …
> IBX-719: Introduced BatchIterator

- eZ/Publish/API/Repository/Tests/ContentService/VersionValidatorTest.php
- eZ/Publish/Core/Repository/Validator/VersionValidator.php
| **JIRA issue**                          | [IBX-175](https://issues.ibexa.co/browse/IBX-175)
| **Type**                                   |bug
Due to the missing `$language` option, while fetching fields to be validated, we end up with a validation error for each content translation, regardless of field value's correctness.
> IBX-175: Fixed invalid VersionValidator errors output when validation fails for multilingual content

- .github/workflows/ci.yaml
- .travis.yml
- composer.json
- eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/FileSizeExtensionTest.php
- eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/FileSizeExtension.php
- phpunit-integration-legacy.xml
| **JIRA issue**                          | [IBX-764](https://issues.ibexa.co/browse/IBX-764)
Includes:
* Re-enabled test for `FileSizeExtension` (https://issues.ibexa.co/browse/IBX-838)
* Part of https://issues.ibexa.co/browse/IBX-764 related to introducing Github Action tests
> [FAST FORWARD] Merged up changes from ezpublish-kernel repository

- composer.json
- eZ/Bundle/EzPublishCoreBundle/Tests/Resources/config/doctrine.php
- eZ/Bundle/EzPublishCoreBundle/Tests/Resources/config/ezpublish.yaml
- eZ/Bundle/EzPublishCoreBundle/Tests/Resources/config/framework.yaml
- eZ/Bundle/EzPublishCoreBundle/Tests/Resources/config/security.yaml
- eZ/Bundle/EzPublishCoreBundle/Tests/Resources/services/fixture-services.yaml
- phpunit-integration-legacy.xml
- src/contracts/Test/IbexaKernelTestCase.php
- src/contracts/Test/IbexaTestKernel.php
- tests/integration/BasicKernelTest.php
| **JIRA issue**                          | [IBX-764](https://issues.ibexa.co/browse/IBX-764)
| **Doc needed**                       | ~yes/no - _depending on whether we feel ok with exposing the test base right now_~ **No, only internal use**
Adds `IbexaTestKernel` & `IbexaKernelTestCase` as base for other packages for wholesome integration tests.
The main selling point of those tests is that they also test our service declarations. They are also easy to expand upon by adding more bundles / services into the test Kernel, and …
> IBX-764: Added Kernel / Repository Test API

- tests/bundle/Core/EventListener/BackwardCompatibleCommandListenerTest.php
- tests/integration/Core/FieldType/User/UserStorage/Gateway/UserDoctrineStorageGatewayTest.php
- tests/lib/Persistence/Legacy/Filter/CriterionQueryBuilder/Content/Type/ContentTypeGroupIdQueryBuilderTest.php
- tests/lib/Persistence/Legacy/Filter/CriterionQueryBuilder/Content/Type/ContentTypeQueryBuildersTest.php
| **JIRA issue**                          | [IBX-850](https://issues.ibexa.co/browse/IBX-850)
| **BC breaks**                          | no, tests are package-internal
This PR fixes incorrect (PSR-{0,4}-incompatible) namespaces for test classes, created by accident.
The classes were moved in a forward-compatible way to the new `Ibexa\*` namespace, so we don't need to maintain BC layer in `ibexa/core`. The placement is based on a future placement of classes being under test.
As a bonus there's small fix of static method invocation, as it does not pollute the diff too much.
Fixed …
> IBX-850: [Tests] Fixed PSR-incompatible test namespaces

- eZ/Publish/Core/Repository/ProxyFactory/ProxyGeneratorInterface.php
| **JIRA issue**                          | N/A
Adds static analysis information to `ProxyGeneratorInterface`, which allows tools like PHPStan to understand that the returned object will have a specific class.
> Added static analysis declaration to `ProxyGeneratorInterface`

- composer.json
| **JIRA issue**                          | n/a
| **Type**                                   | external BC break
| **Target Ibexa version** | v3.3, v4.0
Exact thing as in https://github.com/ibexa/oss/pull/16, but this time I'm adding the conflict to kernel directly - the conflict in `ibexa/oss` is not taken into account when integration tests in the Kernel are run, which results in failed builds:
https://app.travis-ci.com/github/ezsystems/ezplatform-kernel/jobs/534628414
```
1) Warning
The data provider specified for eZ\Publish\API\Repository\Tests\Values\User\Limitation\RolePolicyLimitationTest::testRolePoliciesWithOverlappingLi …
```
> [Composer] Added conflict with symfony/dependency-injection v3.5.7

- eZ/Bundle/EzPublishCoreBundle/EventListener/ViewControllerListener.php
- eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/ViewControllerListenerTest.php
- eZ/Publish/Core/MVC/Symfony/View/Event/BuildViewEvent.php
- src/contracts/Event/View/PostBuildViewEvent.php
- tests/lib/Event/View/PostBuildViewEventTest.php
| **JIRA issue**                          | [IBX-431](https://issues.ibexa.co/browse/IBX-431)
Lock and Unlock feature requires a way to react to building `ContentEditView`. Emitting the event after building the `View` object (whatever `View` object it would be) seems appropriate.
> IBX-431: Added event dispatching after building the View

- eZ/Publish/Core/MVC/Symfony/Security/Authentication/RepositoryAuthenticationProvider.php
| **Type**                                   | bug/improvement
| **Target Ibexa version** | `v4.0`
Fixed issue reported by IDE static code analysis:
`\Symfony\Component\Security\Core\Authentication\Provider\UserAuthenticationProvider::checkAuthentication` returns void so return statement is redundant
> Removed return statement from RepositoryAuthenticationProvider::checkAuthentication

- eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorAdapter/ContentFilteringAdapterTest.php
- eZ/Publish/API/Repository/Tests/Iterator/BatchIteratorAdapter/LocationFilteringAdapterTest.php
- phpunit.xml
| **JIRA issue**                          | Follow-up for [IBX-719](https://issues.ibexa.co/browse/IBX-719)
This PR fixes broken tests introduced via #211. The tests were never executed because they were not a part of the test suites.
The iterator instance is never gonna be the same instance, hence `assertSame` fails. What we need here is a check if the iterators contain the same objects.
> [Tests] Fixed Repository BatchIteratorAdapter tests 

- eZ/Bundle/EzPublishCoreBundle/Tests/Resources/config/doctrine.php
| **JIRA issue**                          | [IBX-1195](https://issues.ibexa.co/browse/IBX-1195)
| **Target Ibexa version** | `v4.0`
Default to in-memory SQLite database for integration tests.
> IBX-1195: Added default value for `DATABASE_URL` for `IbexaTestKernel`

- eZ/Bundle/EzPublishCoreBundle/Tests/Resources/config/ezpublish.yaml
| **JIRA issue**                          | [IBX-1196](https://issues.ibexa.co/browse/IBX-1196)
| **Target Ibexa version** | `v4.0`
Allows `SEARCH_ENGINE` environment variable to be used to select a different search engine than `legacy`.
> IBX-1196: Started respecting `SEARCH_ENGINE` env variable in `IbexaTestKernel`

- eZ/Publish/API/Repository/Values/Content/Query/Criterion.php
| **JIRA issue**                          | N/A
Fixed invalid PHPDoc declaration for `Criterion::$value` to allow proper static analysis in dependent packages.
> Fixed invalid PHPDoc for `Criterion::$value`
